#!/bin/bash

cwd=$(dirname $0)
echo "run in" $cwd


COMMENT="Note: tk_version 8.6.12(or over, from Homebrew repository) can run this app in macOS after Monterey version.
In macOS, it's recommended to install tcl-tk by \"brew install tcl-tk\""

isDarwin=0
darwinWish=/usr/bin/wish

OS=$(uname -s)

if [ "$OS" == "Darwin" ]
then
    isDarwin=1
    echo "$COMMENT"
fi


WISH_PATH=wish
version=0.0

wishes=("$(which -a wish)" "/usr/local/opt/tcl-tk/bin/wish")

for one in ${wishes[@]}
do
    if [ -f $one ]
    then
        if [ $isDarwin -eq 1 ]
        then
            if [ "$darwinWish" == "$one" ]
            then
                continue
            fi
        fi
        cat $cwd/tk_version_1.sh > $cwd/tk_version.sh
        echo exec $one '"$0"' '"$@"' >> $cwd/tk_version.sh
        cat $cwd/tk_version_2.sh >> $cwd/tk_version.sh
        one_version=$($cwd/tk_version.sh 2>/dev/null)
        printf "Found tk version:%7s at %s\n" $one_version $one
        if [[ "$one_version" > "$version" ]]
        then
            version=$one_version
            WISH_PATH=$one
        fi
    fi
done


if [ "$version" = "0.0" ]
then
    echo "No usable wish found"
    exit 1
fi


echo "use (newer) version:" $version


inBG=0
if [ $# -eq 1 -a "$1" = "-bg" ]
then
    inBG=1
fi

if [ "$inBG" -eq 1 ]
then
    $WISH_PATH $cwd/src/LogCatch.tcl --dir $cwd/src &
else
    $WISH_PATH $cwd/src/LogCatch.tcl --dir $cwd/src
fi
